### ISSUE TITLE
VRA Variable reference not working for bigip_ltm_node resource

### ISSUE THREAD

**Issue by rejackson73** [F5Networks/tf-bigip-version0.12#51] opened 2020-03-16 14:09 UTC
We want to use parameters returned from VRA7 as node names for the bigip_ltm_nodes. The challenge is the parameter reference in VRA is...unusual.

The state information returned from VRA, after the creation of a machine, is as follows:
"catalog_item_id" = "7ebedfaf-c429-4610-9465-2e5677f5a8b8"
"catalog_item_name" = "Developer Linux Red Hat 6"
"description" = "Test deployment"
"id" = "f0f290b7-55a8-4e9a-b8be-87284863f1b9"
"request_status" = "SUCCESSFUL"
"resource_configuration" = {
"LinuxRedHat6_VM.VirtualMachine.Network0.Address" = ""
"LinuxRedHat6_VM.VirtualMachine.Network0.NetworkProfileName" = "infradev_tenant_10_172_60_0-22"
"LinuxRedHat6_VM.Vrm.DataCenter.Location" = "STR Datacenter"
"LinuxRedHat6_VM.address" = ""
"LinuxRedHat6_VM.name" = "xstrlaab9893"
"LinuxRedHat6_VM.voya_backup_servicelevel" = "noprotection"
"LinuxRedHat6_VM.voya_cmdbname" = "Developer Test Application"
"LinuxRedHat6_VM.voya_environment" = "Infra Development"
"LinuxRedHat6_VM.voya_puppet_environment" = "cloud_unittest"
}

We need to use the IP address associated with LinuxRedHat6_VM.name parameter as the node address, but we don't get that back from VRA. We can use the DNS provider as follows:
data "dns_a_record_set" "node1" {
host = vra7_deployment.my_vra7_deployment[0].resource_configuration["LinuxRedHat6_VM.name"]
}

However, we also want to use that name as the the name of the node within F5. The name of the node is defined within the bigip_ltm_node resource:
resource "bigip_ltm_node" "node" {
name = "/Common/terraform_node1"

If we use variable string for the VM name, identified above, in the F5 provider resource, we get an error regarding invalid name for the node. This was the expected format:
name = "/Common/${vra7_deployment.my_vra7_deployment[0].resource_configuration[\"LinuxRedHat6_VM.name\"]"

We attempted the following variations of the parameter, but none of them worked.
name = "/Common/${vra7_deployment.my_vra7_deployment[0].resource_configuration[4]}"
name = "/Common/${vra7_deployment.my_vra7_deployment[0].resource_configuration[LinuxRedHat6_VM.name]}"
name = "/Common/${vra7_deployment.my_vra7_deployment[0].resource_configuration['LinuxRedHat6_VM.name]'}"

We do know that if you use the provider with another compute resource, such as AWS, variable is able to be passed through as follows:
name = "/Common/${aws_instance.example[0].public_dns}"

We suspect that the name validation for the bigip_ltm_node resource is having a problem parsing the variable that is necessary for the VRA resource.

**Comment by papineni87** [comment] 2020-03-19 18:52
is this the below error you are seeing ? or different

"must match /Partition/Name and contain letters, numbers or [._-]. e.g. /Common/my-pool. "

If it is above error then there is issue in regex for validating node name, if not then no issue in validation of f5 name

I am not able to reproduce it, can you list out complete config  file ( .tf )

**Comment by rejackson73** [comment] 2020-03-19 19:04
Thanks for the response!

I’ve added John Woods from Voya Financial whom I worked with on this endeavor.  That is indeed the error that we found, and I’m hoping that John can provide the relevant code.  John, the resulting state sections would be good as well so the translated node name can be visible.

Thanks all!
Rob

**Comment by rejackson73** [comment] 2020-03-19 19:21
OK, I was able to provide the code with John’s approval.


resource "bigip_ltm_node" "node" {

  name             = "/Common/${vra7_deployment.my_vra7_deployment[0].resource_configuration[”LinuxRedHat6_VM.name”]}"

  address          = "192.168.30.1"

  connection_limit = "0"

  dynamic_ratio    = "1"

  monitor          = "/Common/icmp"

  description      = "Test-Node"

  rate_limit       = "disabled"

  fqdn             = { address_family = "ipv4", interval = "3000" }

}

The name we were receiving back from the VRA provider is:

  "resource_configuration" = {

    "LinuxRedHat6_VM.VirtualMachine.Network0.Address" = ""

    "LinuxRedHat6_VM.VirtualMachine.Network0.NetworkProfileName" = "infradev_tenant_10_172_60_0-22"

    "LinuxRedHat6_VM.Vrm.DataCenter.Location" = "STR Datacenter"

    "LinuxRedHat6_VM.address" = ""

    "LinuxRedHat6_VM.name" = "xstrlaab9893"

    "LinuxRedHat6_VM.voya_backup_servicelevel" = "noprotection"

    "LinuxRedHat6_VM.voya_cmdbname" = "Developer Test Application"

    "LinuxRedHat6_VM.voya_environment" = "Infra Development"

    "LinuxRedHat6_VM.voya_puppet_environment" = "cloud_unittest"

  }


From: Rob Jackson <rjackson@hashicorp.com>
Date: Thursday, March 19, 2020 at 3:04 PM
To: F5Networks/terraform-provider-bigip <reply@reply.github.com>, F5Networks/terraform-provider-bigip <terraform-provider-bigip@noreply.github.com>
Cc: Author <author@noreply.github.com>, "Woods, J. (John)" <John.Woods@voya.com>
Subject: Re: [F5Networks/terraform-provider-bigip] VRA Variable reference not working for bigip_ltm_node resource (#51)

Thanks for the response!

I’ve added John Woods from Voya Financial whom I worked with on this endeavor.  That is indeed the error that we found, and I’m hoping that John can provide the relevant code.  John, the resulting state sections would be good as well so the translated node name can be visible.

Thanks all!
Rob

**Comment by papineni87** [comment] 2020-03-20 05:24
I guess the value of below expression. 
${vra7_deployment.my_vra7_deployment[0].resource_configuration[”LinuxRedHat6_VM.name”]} is not resolving to  desired value ("xstrlaab9893" ). I just tried expression output directly in node name as below 

resource "bigip_ltm_node" "node" {
  name    = "/Common/xstrlaab9893"
  address = "10.10.10.10"
}

root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip# terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # bigip_ltm_node.node will be created
  + resource "bigip_ltm_node" "node" {
      + address          = "10.10.10.10"
      + connection_limit = (known after apply)
      + dynamic_ratio    = (known after apply)
      + id               = (known after apply)
      + monitor          = "/Common/icmp"
      + name             = "/Common/xstrlaab9893"
      + rate_limit       = (known after apply)
      + ratio            = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_ltm_node.node: Creating...
bigip_ltm_node.node: Creation complete after 0s [id=/Common/xstrlaab9893]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

**Comment by rejackson73** [comment] 2020-03-20 12:17
Thanks for your follow up.  However, we were able to determine through Terraform ‘outputs’ that the long variable was resolving to the desired value.  We were also able to validate that a typical reference to another resource worked.

What I suspect…and this is only suspicion from a person who knows nothing about Go language, is that the BigIP provider is trying to validate the format of the variable reference, before the variable is even evaluated.  Is it possible that the brackets and quotes around ‘LinuxRedHat6_VM.name’ are messing things up?

Thanks againf or your help.
Rob

**Comment by papineni87** [comment] 2020-03-20 15:45
To confirm in the code, whether validation of node name is happening before or after the evaluation of expression, i have added some debug statements in code and tried below config

Here i am using test variable output in node name 

provider "bigip" {
  address  = "xxxx"
  username = "xxx"
  password = "xxx"
}

variable  "test" {
default = "testing"
}

resource "bigip_ltm_node" "node" {
  name    = "/Common/${var.test}"
  address = "10.10.10.10"
}

root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip# terraform apply
2020/03/20 08:17:04 [INFO] Terraform version: 0.12.6  
2020/03/20 08:17:04 [INFO] Go runtime version: go1.12.6
................................
020-03-20T08:17:05.298-0700 [DEBUG] plugin.terraform-provider-bigip: 2020/03/20 08:17:05 [INFO] Initializing BigIP connection
**### 2020-03-20T08:17:05.382-0700 [DEBUG] plugin.terraform-provider-bigip: 2020/03/20 08:17:05 i am here for debug: [/Common/testing]
2020-03-20T08:17:05.382-0700 [DEBUG] plugin.terraform-provider-bigip: 2020/03/20 08:17:05 i am here in debug loop : /Common/testing
2020-03-20T08:17:05.382-0700 [DEBUG] plugin.terraform-provider-bigip: 2020/03/20 08:17:05 i am here for debug match : true**

Terraform will perform the following actions:

  # bigip_ltm_node.node will be created
  + resource "bigip_ltm_node" "node" {
2020/03/20 08:17:05 [DEBUG] command: asking for input: "Do you want to perform these actions?"
      + address          = "10.10.10.10"
      + connection_limit = (known after apply)
      + dynamic_ratio    = (known after apply)
      + id               = (known after apply)
      + monitor          = "/Common/icmp"
      **+ name             = "/Common/testing"**
      + rate_limit       = (known after apply)
      + ratio            = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.


From the above debug statements, it is clear that in the code where validation of node name is happening after it resolved the expression ( /common/testing ) i.e., var.test value is resolved to "testing" and then it is validated by regular expression.

so can we try taking that big expression to some variable , and use that variable in node name. So i hope that when variable is referenced, it will resolved in variable in itself and then it will be used in node name.

variable test {
default = ${vra7_deployment.my_vra7_deployment[0].resource_configuration[”LinuxRedHat6_VM.name”]}

}

resource "bigip_ltm_node" "node" {
  name             = "/common/$var.test"
......
}


Are we using multiple providers ( VRA7, bigip ) in same .tf file ?  If so we have to use depends_on, to make sure VRA7 provider output variables are calculated fully and then been used in bigip provider.

**Comment by rejackson73** [comment] 2020-03-20 16:08
Hmmm…now I’m super confused.  The VRA resource management is in a separate .tf file, and even without the ‘depends_on’ I know that Terraform is running them in the proper order.  We had even gone back a few times, after the VRA portion ran, and updated the BigIP provider configuration, so I’m sure the name was available and resolving.  I’m stumped.

@Woods, J. (John)<mailto:John.Woods@voya.com>, what do you think about making another run at it, from start to finish, with full debug mode?

Rob

**Comment by papineni87** [comment] 2020-03-24 03:24
@rejackson73  have you had a chance to run it again ? Are you still seeing the problem ?

**Comment by rejackson73** [comment] 2020-03-24 13:01
Greetings,

Sorry for the delayed reaction.  The customer has been working on some 
other priority items and we had another complication that prohibited us 
from moving forward for now.  The plan next is to make a full run, from 
start to finish, in debug mode on Terraform so we can hopefully further 
analyze the flow.

Rob

------ Original Message ------

**Comment by rejackson73** [comment] 2020-03-25 16:17
OK, so we increased the debug on Terraform and we are seeing the same 
result…


2020/03/25 15:08:19 [DEBUG] Resource state not found for node 
"bigip_ltm_virtual_server.http", instance bigip_ltm_virtual_server.http

2020/03/25 15:08:19 [DEBUG] ReferenceTransformer: 
"bigip_ltm_virtual_server.http" references: []

2020/03/25 15:08:19 [DEBUG] Resource state not found for node 
"bigip_ltm_node.node2", instance bigip_ltm_node.node2

2020/03/25 15:08:19 [DEBUG] ReferenceTransformer: "bigip_ltm_node.node2" 
references: []

2020/03/25 15:08:19 [DEBUG] Resource state not found for node 
"bigip_ltm_node.node1", instance bigip_ltm_node.node1

2020/03/25 15:08:19 [DEBUG] ReferenceTransformer: "bigip_ltm_node.node1" 
references: []

2020/03/25 15:08:19 [DEBUG] Resource state not found for node 
"bigip_ltm_pool.pool", instance bigip_ltm_pool.pool

2020/03/25 15:08:19 [DEBUG] ReferenceTransformer: "bigip_ltm_pool.pool" 
references: []

2020/03/25 15:08:19 [ERROR] <root>: eval: *terraform.EvalDiff, err: 
"name" must match /Partition/Name and contain letters, numbers or [._-]. 
e.g. /Common/my-pool

2020/03/25 15:08:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: 
"name" must match /Partition/Name and contain letters, numbers or [._-]. 
e.g. /Common/my-pool

2020/03/25 15:08:19 [ERROR] <root>: eval: *terraform.EvalDiff, err: 
"name" must match /Partition/Name and contain letters, numbers or [._-]. 
e.g. /Common/my-pool

2020/03/25 15:08:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: 
"name" must match /Partition/Name and contain letters, numbers or [._-]. 
e.g. /Common/my-pool

2020/03/25 15:08:19 [WARN] Provider "registry.terraform.io/-/bigip" 
produced an invalid plan for bigip_ltm_virtual_server.http, but we are 
tolerating it because it is using the legacy plugin SDK.

     The following problems may be the cause of any confusing errors from 
downstream operations:

       - .state: planned value cty.StringVal("enabled") does not match 
config value cty.NullVal(cty.String)

       - .mask: planned value cty.StringVal("255.255.255.255") does not 
match config value cty.NullVal(cty.String)

       - .source: planned value cty.StringVal("0.0.0.0/0") does not match 
config value cty.NullVal(cty.String)



Error: "name" must match /Partition/Name and contain letters, numbers or 
[._-]. e.g. /Common/my-pool



   on main.tf line 27, in resource "bigip_ltm_node" "node1":

   27: resource "bigip_ltm_node" "node1" {







Error: "name" must match /Partition/Name and contain letters, numbers or 
[._-]. e.g. /Common/my-pool

------ Original Message ------
From: "Rob Jackson" <rjackson@hashicorp.com>
To: "F5Networks/terraform-provider-bigip" 
<reply@reply.github.com>; 
"F5Networks/terraform-provider-bigip" 
<terraform-provider-bigip@noreply.github.com>
Cc: "Mention" <mention@noreply.github.com>; "Woods, J. (John)" 
<John.Woods@voya.com>
Sent: 3/24/2020 9:01:41 AM
Subject: Re[2]: [F5Networks/terraform-provider-bigip] VRA Variable 
reference not working for bigip_ltm_node resource (#51)

**Comment by focrensh** [comment] 2020-03-26 15:30
Tracking with TER-270 internally.

**Comment by papineni87** [comment] 2020-03-26 17:53
@rejackson73 i am still not able to reproduce locally, so i would suggest to contact F5 official support (https://www.f5.com/services/support)  to enable further debugging ( live debug, as issue is reproducible only in user location ). I am sure that official F5 support engineers will help in all the ways  for speedy resolution.

**Comment by papineni87** [comment] 2020-03-27 03:43
@rejackson73 Just another alternative , you can raise a service request or call up F5 support number and they will guide you on how to raise an SR

**Comment by focrensh** [comment] 2020-05-22 15:24
Closing due to not being able to reproduce. Please open a support case as mentioned above if this is still an ongoing issue. Thanks,

**Closed as completed by focrensh** 2020-05-22 15:24 UTC
Labels: question
